# Generated by Django 2.1.5 on 2019-01-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
    ]
