# Generated by Django 2.1.5 on 2019-01-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_remove_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
